import {useState} from 'react';
import {TRAINING,type Progress} from '../lib/training';
import {type Model} from '../lib/policy';
import {type Benchmark} from '../lib/benchmark';
export type History=Omit<Progress,'model'>[];
export function downloadJson(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function TrainingBench({model,history,busy,status,benchmark,onTrain,onStop,onBenchmark,onImport,onRestore}:{model:Model|null;history:History;busy:'train'|'benchmark'|null;status:string;benchmark:Benchmark|null;onTrain:(seed:number)=>void;onStop:()=>void;onBenchmark:()=>void;onImport:(file:File)=>void;onRestore:()=>void}){
 const [seed,setSeed]=useState('20260912');const last=history.at(-1);const max=Math.max(1,...history.map(p=>Math.max(p.bestFitness,p.validation)));
 const path=(key:'meanFitness'|'validation')=>history.map((p,i)=>`${i?'L':'M'}${10+i/Math.max(1,TRAINING.generations-1)*580},${108-p[key]/max*92}`).join(' ');
 return <section className="training-bench" aria-labelledby="training-title"><div className="bench-heading"><div><h2 id="training-title">TRAINING / NEUROEVOLUTION</h2><p>Real rollouts. Score-based weight updates. No teacher or scripted action fallback.</p></div><span role="status">{status}</span></div>
 <div className="bench-controls"><label>Training seed <input aria-label="Training seed" type="number" min="1" max="4294967295" value={seed} disabled={!!busy} onChange={e=>setSeed(e.target.value)}/></label><button disabled={!!busy||!Number.isInteger(Number(seed))||Number(seed)<1||Number(seed)>4294967295} onClick={()=>onTrain(Number(seed))}>Train from scratch</button>{busy&&<button onClick={onStop}>Stop</button>}<button disabled={!!busy||!model} onClick={onBenchmark}>Benchmark current model</button><button disabled={!!busy} onClick={onRestore}>Restore published model</button><button disabled={!model} onClick={()=>downloadJson('flyjump-model.json',model)}>Export model</button><label className="import-model">Import model<input aria-label="Import model" type="file" accept=".json,application/json" disabled={!!busy} onChange={e=>{const file=e.target.files?.[0];if(file)onImport(file);e.target.value='';}}/></label></div>
 <div className="training-readout"><div><strong>{last?.generation??0} / {TRAINING.generations}</strong><span>GENERATIONS THIS RUN</span></div><div><strong>{(last?.episodes??0).toLocaleString('en-US')}</strong><span>EVALUATED EPISODES</span></div><div><strong>{Math.round(last?.validation??model?.validation??0)}</strong><span>CHAMPION VALIDATION SCORE</span></div><div><strong>64 → 8</strong><span>CANDIDATES → ELITES</span></div></div>
 {history.length>0?<><svg className="training-chart" viewBox="0 0 600 125" role="img" aria-label="Training population mean and champion validation score over generations"><line x1="10" y1="108" x2="590" y2="108" stroke="#344150"/><path d={path('meanFitness')} fill="none" stroke="#8499ae" strokeWidth="2"/><path d={path('validation')} fill="none" stroke="#afd3b3" strokeWidth="2"/><text x="12" y="13" fill="#92a4b5" fontSize="10">{Math.round(max)} score</text></svg><p>Blue: population mean (training courses). Green: champion validation score. Different course sets.</p><button onClick={()=>downloadJson('flyjump-training.json',{algorithm:'CEM neuroevolution',seed:model?.trainingSeed,config:TRAINING,history})}>Export training log</button></>:<p className="training-empty">Start from random weights to watch learning. The published checkpoint is already trained; ordinary play only runs inference.</p>}
 <p>8 structured game observations → 12 tanh neurons → 3 action scores. CEM optimizes distance over up to 180 seconds per course. This is an artificial policy controlling the fly rig, not a simulation of its biological brain.</p>
 {benchmark&&<div className="benchmark-result"><h3>HELD-OUT COURSES / {benchmark.config.seeds.length} × {benchmark.config.seconds}s</h3><div className="benchmark-table"><table><thead><tr><th>Controller</th><th>Completed</th><th>Mean survival</th><th>Mean score</th></tr></thead><tbody>{benchmark.results.map(r=><tr key={r.name}><th>{r.name}</th><td>{r.survived} / {r.courses}</td><td>{r.meanSeconds.toFixed(1)}s</td><td>{Math.round(r.meanScore)}</td></tr>)}</tbody></table></div><p>Fixed seeds excluded from training and model selection. Results describe this checkpoint and environment, not general intelligence.</p><button onClick={()=>downloadJson('flyjump-benchmark.json',benchmark)}>Export benchmark</button></div>}
 <div className="bench-downloads"><a href="/benchmarks/model.json" download>Published model</a><a href="/benchmarks/training.json" download>Published training log</a><a href="/benchmarks/benchmark.json" download>Published benchmark</a><a href="https://github.com/cobanov/flyjump/blob/main/docs/experiment.md">Experiment notes ↗</a></div>
 </section>;
}
